### ISSUE TITLE
It is not support Chinese?

### ISSUE THREAD

**Issue by JhonYoung** [clarketm/TableExport#1]
I  tryed many plugins,yours is the best,I think.  but it not support chinese, will you  fix this problem?

**Comment by clarketm** [comment]
Thank you. I am glad you like the plugin. Let me see what I can do to resolve the compatibility issue. Can you elaborate more on specifically what components are unsupported or provide me with an example webpage that displays the problem?

**Comment by clarketm** [comment]
Is the plugin not recognizing Chinese characters when it parses the table?

**Comment by JhonYoung** [comment]
yes. when i export a table as excel, which contain Chinese like this
<table id="tblExport">
            <thead>
                <tr>
                    <th>order</th>
                    <th>姓名</th>
                    <th>年龄</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>张三</td>
                    <td>22</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>李四</td>
                    <td>30</td>
                </tr>
        </tbody>
</table>

the Chinese parts parses to something strange.

**Comment by clarketm** [comment]
JhonYoung, I changed the character encoding for all file formats from utf-8 to utf-16 to allow for accurate parsing of Chinese characters. Please let me know if the updated source code (v3.1) resolves the issue. I tested on Mac Excel 2011, Mac Excel 2016, and Windows Excel 2013 with positive results. It this doesn't fix the problem please let me know what version of Excel you are using and on what OS.

**Comment by TangMonk** [comment]
Chinese still  Not works on 3.2.5
