### ISSUE TITLE
[BUG] Excel recognise the file as .txt instead of .csv

### ISSUE THREAD

**Issue by mankinchi** [clarketm/TableExport#106]
I use the plugin to do simple export like this: `$('#blank').tableExport({
            type: 'csv',
            csvEnclosure: '"'
        });`. However, when I open the file in Excel, Excel recognise the file as .txt (when I use "save as"). I think because of this, when I hit "Save" on Excel, it automatically changes the format from comma to tab delimiter. Can you look into this? Thanks

**Comment by clarketm** [comment]
@mankinchi – This [TableExport](https://github.com/clarketm/TableExport) is not the same [plugin you are using](https://github.com/hhurz/tableExport.jquery.plugin). We use `formats` rather than `type` to specify file format.
