### ISSUE TITLE
jQuery dependency warning (@5.0.0)

### ISSUE THREAD

**Issue by pbalzano91** [clarketm/TableExport#122]
![jquerydep](https://user-images.githubusercontent.com/6012986/37524250-0db27c76-2908-11e8-8926-ba89e310bd9e.png)
Getting this warning at version 5.0.0 (imported with npm, bundling with webpack).

**Comment by martinhartwig** [comment]
Why did you close this issue? What was your solution?

**Comment by aleksme** [comment]
I think jquery is Optional... but it is not

**Comment by jhadenfeldt** [comment]
jQuery is listed as a peer-dependency. Since npm3,[ peer-dependencies aren't installed automatically anymore](https://github.com/npm/npm/issues/6565). If you want to get rid of the warning, you'll have to add jQuery to your own `package.json`:

`npm i -s jquery`
