### ISSUE TITLE
XLSX is disabled in mobile devices

### ISSUE THREAD

**Issue by esaesa** [clarketm/TableExport#131]
This sample https://tableexport.v3.travismclarke.com/examples/exportButtons.html and its modified v5 is not showing the xlsx button with a console warning tableexport.min.js:19 "xlsx" requires "js-xlsx".

![image](https://user-images.githubusercontent.com/5354709/39246258-521f3446-4896-11e8-8108-28c589904e2b.png)

I searched the code and i found 

    var _isEnhanced = (function () {
            return function (key) {
                return (
                    XLSX
                    && !_isMobile
                    && !(TableExport.prototype.formatConfig[key].enforceStrictRFC4180)
                );
            }
        })();
which will return always false in mobile devices and so generate the error as dependency is required although it is loaded correctly and working in other older examples.
You can note in the image only two buttons instead of 3 as desktop version.

Update: 25,Apr. 2014
_________________________
* Disabling this function solved the disappearance problem but the generated file is not correct.
* I found another working example but it was an old version https://www.jqueryscript.net/demo/Exporting-Html-Tables-To-CSV-XLS-XLSX-Text-TableExport/

**Comment by clarketm** [comment]
@esaesa – I will investigate because this doesn't look correct. I will say that mobile support is not *fully* cross-platform (e.g. Safari mobile is a nightmare to work with, and some of the less common/popular mobile browsers).
