### ISSUE TITLE
$.fn.tableExport.ignoreCSS Doesn't Work - TableExport.prototype.ignoreCSS does - using jQuery

### ISSUE THREAD

**Issue by own3mall** [clarketm/TableExport#143]
I'm using the latest version of TableExport v5 with jQuery 3.x, and when I use the below line, it doesn't work.

```
$.fn.tableExport.ignoreCSS = [".tableexport-empty", ".other-empty-class"];
```
However, this worked:
```
TableExport.prototype.ignoreCSS = [".tableexport-empty", ".other-empty-class"];
```

I would assume they should both work.  I called them right before I initialized a table export instance using:

```
$('.myTable').tableExport();
```

**Comment by clarketm** [comment]
@own3mall – You are correct, thank you for identifying this. I have a fix in the latest release [v5.0.3]().
