### ISSUE TITLE
Input value

### ISSUE THREAD

**Issue by smoothblood** [clarketm/TableExport#15]
I use your plugin, it is easy compared to other plug-in, but I have a problem, it does not retrieve the value of an input text in a **td**.

Cheers and thank you for your time!

**Comment by clarketm** [comment]
Can you elaborate a bit more on this issue – or provide an example? I am not sure I understand quite what you mean.

**Comment by clarketm** [comment]
I am closing this issue as **invalid** for lack of clarity with 60+ days without a reply.

**Comment by ikiller1** [comment]
<table id="tabletest" style="text-align:center" border="1" >
  <caption>custumer detail</caption>
  <tr>
    <th style="background-color:PaleTurquoise" colspan="1">order id</th>
    <td colspan="1"><input type="text" id="_50A" name="_50A" value=QWEEEWQEQ></td>
	<td><a id="link" href="">LinkToOrder</a></td>
  </tr>
  <tr>
	<th style="background-color:PaleTurquoise" colspan="1">name</th>
    <td colspan="1"><input type="text" name="name" value=陈></td>
	<th style="background-color:PaleTurquoise" colspan="1">日期</th>
    <td colspan="1"><input type="date" name="date" value=2017-05-27></td>
	<th style="background-color:PaleTurquoise" colspan="1">address</th>
    <td colspan="1"><input type="text" name="address" value=></td>
  </tr>
<body>
</table>

Like this, the data in tag "input " could not export to excel format.

**Comment by fuzunspm** [comment]
> ```
> <td colspan="1"><input type="date" name="date" value=2017-05-27></td>
> <td colspan="1"><input type="text" name="address" value=></td>
> ```
> 
> Like this, the data in tag "input " could not export to excel format, although it is in a table
> @clarketm

could you find a solution to this?
