### ISSUE TITLE
Position not working

### ISSUE THREAD

**Issue by bryandandan** [clarketm/TableExport#151]
Hi,

Whether I put position bottom or top, the buttons always appear on the bottom.
I first tried this on a bootstrap table, then on a simple table to see if bootstrap was the problem.
But both yield the same result

I looked at #9 but didn't understand what is the link with CSS.

Kindly advise

Bryan

**Comment by clarketm** [comment]
@bryandandan – There is a css file that you can be included for buttons. The [README](https://github.com/clarketm/TableExport/blob/master/README.md) does not do a great job of delineating this, so I will update the docs to make it more clear and provide an easier way to reference the stylesheet. 

The css stylesheet is in the `dist` directory. You can link to it via `unpkg` (below): 
CSS: https://unpkg.com/tableexport@5.0.3/dist/css/tableexport.css
