### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by RayXia95** [clarketm/TableExport#153]
This is a pretty solid library!

However, when I am exporting to excel, the cell automatically formats my string, e.x. 'Hello World 2018-3' to 3/1/2018 and I lose the data of 'Hello World' when the sheet actually downloads. Is this intend? Could there be an API to customize the format of the cell before download.

Best,
Ray

**Comment by stgogm** [comment]
I believe this is what you're looking for https://tableexport.v3.travismclarke.com/examples/cell-data-types.html

**Comment by clarketm** [comment]
@RayXia95 - TableExport attempt to intelligently coerce cell types based on their content using a customizable [`typeConfig`](https://github.com/clarketm/TableExport/blob/master/dist/js/tableexport.js#L320) with predicate functions to determine which type to apply.

The easiest way to *force* a specific type is to apply a type class:

|  type | classname | 
| :------: | :------: | 
| string | `tableexport-string` |
| number | `tableexport-number` |
| boolean | `tableexport-boolean` |
| date | `tableexport-date` |

**e.g.**
```html
<table>
        ...
        <td class="tableexport-string">Hello World 2018-3</td>
        ...
</table>
```
