### ISSUE TITLE
Specific column of string becomes date and ignores text

### ISSUE THREAD

**Issue by mcsmithers** [clarketm/TableExport#154]
I am loving this tool, however, it seems that I have a column that's supposed to be string turning into dates when exported to Excel.

For example, 
```
Taboola_Desktop_UK   2240
Taboola_Tablet_UK 2244
Taboola_Tablet_AU 2590
Taboola_Tablet_CAN 3792
Taboola_Mobile_UK 6318
Taboola_Mobile_US 6470
Taboola_Tablet_US 6516
Taboola_Desktop_UK 6566
Taboola_Desktop_US 6742 (dont drop)
Taboola_Desktop_UK 6746
```

becomes 

```
1/1/40
1/1/44
1/1/90
1/1/92
1/1/18
1/1/70
1/1/16
1/1/66
1/1/42
1/1/46
```

`TableExport.prototype.typeConfig.date.assert = function(value) { return false; };` helps this, however that means all my other columns including ones that are dates and numbers then become text.  If there any way to make a specific column be a type that will be processed as string rather than the entire table?

**Comment by akindemirci** [comment]
"You can still explicitly designate a cell as a date using the tableexport-date CSS class."
https://github.com/clarketm/TableExport/issues/82#issuecomment-325004263

Or you can designate the cells you mentioned above as string with "tableexport-string" CSS class.

**Comment by stgogm** [comment]
Take a look at https://tableexport.v3.travismclarke.com/examples/cell-data-types.html

**Comment by clarketm** [comment]
@mcsmithers – Please refer to #153 . You can leverage the type classes (or change the `assert` function like you did) to override the **default** functionality.
