### ISSUE TITLE
Error jszip is not a constructor

### ISSUE THREAD

**Issue by decaller** [clarketm/TableExport#18]
Hello there!

I'm tried to use this plugin in ember and install it with bower.
After inputting app.import in ember-cli-build.js and calling it via constructor I got an error 'jszip is not a constructor'.
Did I do something wrong in installation?
Or should I use it in specific way?

**Comment by clarketm** [comment]
Was this problem resolved with [v3.2.9](https://github.com/clarketm/TableExport/tree/v3.2.11): fix UMD factory syntax for AMD and CJS formats?

**Comment by clarketm** [comment]
I am closing this issue as **fixed** (90+ days without a reply). If this is not the case please reopen.
