### ISSUE TITLE
Apply style in excel.

### ISSUE THREAD

**Issue by pjain9390** [clarketm/TableExport#19]
I am generating the XLSX formate of excel , I want to use same style which I have received from HTML string.
 Please suggest Its important for me.

**Comment by clarketm** [comment]
I am closing this issue as a duplicate of: 
> **#12: How to apply styles to excel file?**

**Comment by clarketm** [comment]
I am closing this issue as a duplicate of: 
> **#12: How to apply styles to excel file?**
