### ISSUE TITLE
Single quote character in cell breaks CSV export

### ISSUE THREAD

**Issue by strelok1** [clarketm/TableExport#2]
In the example page (http://www.clarketravis.com/tableexport/) the CSV export is cut off completely after (and including) the single quote character.

```
"Rank","Country","Population","% of world population","Date"
"1","中华人民共和国 (People
```

XLSX export is fine.

OS: Windows 7 64-bit
Tried browser: 
- Chrome 49.0.2623.87 m
- Firefox 38.0.1

**Comment by clarketm** [comment]
@strelok1 - Thanks for reporting this issue. The latest patch release (v3.1.2) fixes this premature cell termination caused by single quote characters when exporting to xls, csv, and txt formats.
