### ISSUE TITLE
Error with file format and extension on export to Excel

### ISSUE THREAD

**Issue by pkprosol** [clarketm/TableExport#23]
The file format and extension of 'leaderboard-table (1).xls' don't match.

**Comment by clarketm** [comment]
Can you elaborate a bit more ... are you saying that the `.xls` file format is invalid? What about the `.xlsx` Excel format.

**Comment by clarketm** [comment]
I am closing this issue as **fixed** (90+ days without a reply). If this is not the case please reopen.

**Comment by eiranix** [comment]
Having the same issue mentioned here. When you open an exported XLS file Excel gives the error:

> The file you are trying to open, 'export.xls', is in a different format than specified by the file extension. Verify that the file is not corrupted and is from a trusted source before opening the file. Do you want to open the file now?

The file will open upon selecting Yes.
The xls from your demo page does the same thing...

**Comment by francoisgcouillard** [comment]
For my part when I use the library to automatically create buttons, exporting as xlsx it works without problems.

The Excel error happens when I make custom buttons.

**Comment by francoisgcouillard** [comment]
Starting with this example https://github.com/clarketm/TableExport/blob/master/examples/exportButtons.html and changing xls to xlsx, it makes the error.
