### ISSUE TITLE
The example doesn't work on IE and Safari

### ISSUE THREAD

**Issue by miritm** [clarketm/TableExport#25]
Any idea why?
In IE11 I get the following error: SCRIPT438: Object doesn't support property or method 'startsWith'
How do I solve that?

Thank you.

**Comment by miritm** [comment]
Thank you, it's working now in Firefox but it is still not working in Safari.
Please advise.

**Comment by miritm** [comment]
The example on your page is still not working but I downloaded the script again and it worked in Safari, but I can't save it without a name just to open it, how can I name the file for Safari?
Thank you!

**Comment by clarketm** [comment]
It appears that *full* support for Safari is not available (so, I will make the correction in the docs). I am not a heavy Safari user so I need to experiment a bit with the browser mechanics, in addition, I will look for any updates to [FileSaver.js](https://github.com/eligrey/FileSaver.js/) and determine if the current state of the project is capable of allowing for filename customization (like with the other browsers). If not, I might be able to free up the time to look into the mechanics of the [Blob API](https://developer.mozilla.org/en-US/docs/Web/API/Blob) and what I can do. 

Aside from the filename not changing, are there any other shortcomings in user experience with Safari or across any of the other browsers you have used/tested?

**Comment by miritm** [comment]
I just testes in 4 browsers:
1) Chrome- works fine.
2) IE- works fine.
3) Firefox- works fine.
4) Safari- the download works but it gets saved as "Unknown", it looks like it doesn't recognize the file extension and therefor the Open option doesn't work.

-Could that be fixed?
-Is there anyway to just download my table on button click instead of generating a button "Export to XLSX"? Directly downloading the file.

Thank you.

**Comment by miritm** [comment]
Hi,

Any update on this?

Thanks.

**Comment by clarketm** [comment]
At the moment (TableExport [v3.3.1](https://github.com/clarketm/TableExport/tree/v3.3.1)), `xlsx` and `xls` support is being blocked ([fix #242](https://github.com/eligrey/FileSaver.js/issues/242)) by the lack of native support for the [HTML5 download attribute](http://caniuse.com/#feat=download) and [service workers](http://caniuse.com/#search=service%20workers). As you know, by including the [Blob.js](https://github.com/clarketm/Blob.js) polyfill, you can add limited support for these two file types with the caveat that the filename will always be `Unknown` and the file extension will be striped off.

The future Safari release specs look promising; [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) includes native support for both the [HTML5 download attribute](http://caniuse.com/#feat=download) and [service workers](http://caniuse.com/#search=service%20workers).

It looks like the best options at the moment are either:
1. Conditionally limit the file types to only `csv` and `txt` on Safari.
2. Include the [Blob.js](https://github.com/clarketm/Blob.js) polyfill __and__ instruct the user of the caveat (`Unknown` filename without extension) in the UI.
3. Hang tight for the next [Safari release or feature patch](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html).

**Comment by clarketm** [comment]
Safari 10+ now has native File API [support](http://caniuse.com/#feat=fileapi), including custom file naming. 

For legacy versions (e.g.  Safari 6), representing approx. [0.1% of users](http://caniuse.com/usage-table) the issues I mentioned [above](https://github.com/clarketm/TableExport/issues/25#issuecomment-261837607) still hold true. 

<img width="629" alt="screen shot 2017-05-05 at 7 09 52 pm" src="https://cloud.githubusercontent.com/assets/9957358/25769109/7a3b7db4-31c6-11e7-9147-47d39bdf2986.png">
