### ISSUE TITLE
issue with requirejs

### ISSUE THREAD

**Issue by blaisefonseca** [clarketm/TableExport#28]
Hi,

I am trying to use TableExport with requirejs, however i get a error `XLSX.utils.encode_cell is not a function` when any export button is clicked. can you please tell me what am I doing wrong here? i have uploaded  sample code on https://jsbin.com/fivurayodi/3/edit?html,js,console,output

thank you.

**Comment by clarketm** [comment]
TableExport requires [xlsx-core.js](https://github.com/SheetJS/js-xlsx) by [SheetJS](https://github.com/SheetJS)
### npm
```shell
npm install xlsx
```
### bower
```shell
bower install js-xlsx
```
### browser (CDN)
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.core.min.js">/<script>
```

**Comment by clarketm** [comment]
On second though, it looks like the issue is seeded in the `blobjs` and `file-saver` modules. I still need to do some testing, but in the meantime, a working example can be found [here](https://github.com/clarketm/tableexport_requirejs_app).
