### ISSUE TITLE
utf8 encoding

### ISSUE THREAD

**Issue by zelo12000** [clarketm/TableExport#30]
hello, i have problem with encoding, when i try to export table to xsl spreadsheet. When i have in table words that contains ľčščžýá it replaces it with weird characters. I know it is an encoding issue. I also tried to set default parameter $.fn.tableExport.charset = "charset=utf-8"; but this didnt help me.

**Comment by clarketm** [comment]
@zelo12000 – Can you please provide a link to the source or some context on the application environment in which you are implementing the plugin? 

Often times, the issue can be remedied by adding the the [`js-xlsx`](https://github.com/clarketm/js-xlsx) dependency to your project, for example, if you have a basic static web project, then you can simply add the [`xlsx.core.js`](https://github.com/clarketm/js-xlsx/blob/master/xlsx.core.min.js) script to your project. Consult this [reference](https://www.travismclarke.com/tableexport/#dependencies). Let me know if the problem persists.

**Comment by zelo12000** [comment]
thanks a lot mate ! 
i moved xlsx.core.js **BEFORE** the FileSaver.js and now it is working.
