### ISSUE TITLE
Post back occurs in asp.net web page

### ISSUE THREAD

**Issue by Jo-Geek** [clarketm/TableExport#31]
I am fetching a table through jQuery AJAX and then invoke this plugin on the fetched table, it displays the export options as expected. However when I click on it, a post back occurs and the fetched table clears off. Is there a way this plugin may still export without triggering a post back.

**Comment by clarketm** [comment]
@Jo-Geek 
It should not be **POST**ing back. The only _native_ situation where this would happen is if an event in TableExport was triggering a "submit" handler on the client-side. 

> _e.g. form "submit" in response to the "change" of an input._

If this is the case, then I can likely suppress event bubbling for the trigger and fix your problem.

**Can you provide the source code?**

**Comment by Jo-Geek** [comment]
This is the grid which is fetched:
```
<div id='divAJAX'>
    <asp:GridView runat="server" ID="grdOrders" CssClass="table table-bordered"/>
</div>
```
The above table is on a webpage `viewOrders.aspx`.

I am fetching the mentioned table through jQuery AJAX to `Default.aspx` in the following div:

```
<div class="table-responsive" id="grdOrdersContainer"></div>
```

AJAX Code:
```
$.ajax({
    ...
    ...
    success: function(data){
        var grd = $('#divAJAX',data).html();
        $('#grdOrdersContainer').html(grd);
    }
})
```

The grid has no other events associated with it.
As its an ASP.NET page the whole webpage is inside a `form` tag.

**P.S.:**
I tried to alter your plugin to add an `a` tag instead of the `button` tag. The `a` did not post back, but the `button` did!

Maybe the `button` tag is the reason of the post back?

**Comment by clarketm** [comment]
@Jo-Geek – I don't think is would be a problem to change the `button` tag to an `a` tag. I am currently working on #40 which should (when complete) supply a robust solution to the issue – allowing for customization of the structure, design, and placement of the export buttons.

**Comment by clarketm** [comment]
Custom triggers, custom buttons, and even no buttons/anchors are now fully featured #40.
