### ISSUE TITLE
Not able to sum number

### ISSUE THREAD

**Issue by Naitik-Shah** [clarketm/TableExport#32]
When i am downloading table with numeric value it show **"the number in the cell is formatted as text or preceded by an apostrophe"** in downloaded excel it should be number format so i can do grouping, sum and all..

**Comment by danielgregorywilson** [comment]
I believe I have solved this problem, allowing you to add a 'te-number' class to your table cells so they can be formatted how you want them:

https://github.com/clarketm/TableExport/pull/37

**Comment by Naitik-Shah** [comment]
Thanks for response 
in your committed file i am phasing  **excel found unreadable content** when i open the excel and row/column span problem

**Comment by danielgregorywilson** [comment]
Could you post the HTML content you are trying to export when you encounter the problem? I would be happy to take a look.
