### ISSUE TITLE
Customize button

### ISSUE THREAD

**Issue by Alplob** [clarketm/TableExport#34]
Hello, 

I am looking for a way to override default css bootstrap classes and button content, without modifying the source of the plugin.

Per example, I am looking for a way to override the class **btn-default** with **btn-link** in the settings of TableExport. I saw that the following method is described in the documentation, but I made some tests and it seems it does not hava any effect, wherever I put it in my script (befaire initializing TableExport or after):
`$.fn.tableExport.bootstrap = ["btn", "btn-link", "btn-toolbar"];`

Same for this method, where I just replaced the buttonContent text for localization reason:
```
$.fn.tableExport.xlsx = {
    defaultClass: "xlsx",
    buttonContent: "Excel",
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    fileExtension: ".xlsx"
};
```

Could you please let me know how to use these 2 methods?

Thanks!

**Comment by clarketm** [comment]
@Alplob – I am working on a *complete* API refactor for customizing the buttons (please check out #40 for more info on the status of this update).

I have been lagging a bit in updating the documentation (I will get this fixed soon!). The proper way to change a setting is not via the **TableExport** `prototype`:

e.g.
```html
<script src="path/to/tableexport.js"></script>
```
...
```js
...
/* change the `bootstrap` setting */
TableExport.prototype.bootstrap = ["btn", "btn-link", "btn-toolbar"];

/* initialize TableExport */
$('table').tableExport();
```

**Comment by Alplob** [comment]
Perfect, thanks a lot for your feedback!
