### ISSUE TITLE
it can‘t support edge 

### ISSUE THREAD

**Issue by tosakarin** [clarketm/TableExport#35]
i test it on https://www.travismclarke.com/tableexport/
it can't support edge

**Comment by clarketm** [comment]
@tosakarin  – thanks for your interest in [TableExport](https://github.com/clarketm/TableExport).

Please help me better understand the context by answering a few questions, then I will try to get the issue resolved:

- [ ] Which file formats do **not** work in Edge? (e.g. `.xlsx`, `.xls`, `.csv`, `.txt`)
- [ ] Which version of [TableExport](https://github.com/clarketm/TableExport) are you experiencing this issue with?

**Comment by clarketm** [comment]
Extensive testing has been done from IE 8 up to Edge and there doesn't appear to be any issues, especially not with Edge. If you can provide an example, then I will reopen this issue.
