### ISSUE TITLE
i am confused with the usage of  tableexport

### ISSUE THREAD

**Issue by owen-carter** [clarketm/TableExport#39]
forgive my poor english;
i am confused with the usage of  tableexport:

- i must use it with the four default buttons  ?
- has it provide some api for me to pass the data  and generate the file and donwload it ?
- just like T.parse(data).save('filename','xls')

and actually it is very useful ,because generate a xecel file is rather rough with xlxs.js.
so , thanks for share this

@PeterDaveHello @clarketm

**Comment by PeterDaveHello** [comment]
I'm not the author, not sure if you tagged me wrong 😄

**Comment by clarketm** [comment]
@owen-carter - I know this is long-awaited, but I have updated the docs with specific usage scenarios as well as a plethora of examples. Check them out https://tableexport.v4.travismclarke.com/
