### ISSUE TITLE
Force Download

### ISSUE THREAD

**Issue by JamoCA** [clarketm/TableExport#4]
The "txt" format opens a plain text page instead of a forced download.  The "xlsx" export provides me with a default option to "open" the file, but when I do that, there's nothing displayed... it must be saved first.

I normally use the `application/unknown` mime type to force downloads regardless of the file extension.  Could you add an option to force an unknown" mime type and save instead of hoping that the user is knowledgeable enough not to try "opening" it each time? (Otherwise, I'll get multiple reports from users indicating that they found a new web application error.)

**Comment by clarketm** [comment]
The [FileSaver.js](https://github.com/eligrey/FileSaver.js/) implementation in the [v3.2.0 release](https://github.com/clarketm/TableExport/releases/tag/v3.2.0) that I mentioned in [Custom Button/Triggers #3](https://github.com/clarketm/TableExport/issues/3) should resolve any conflicts with MIME type. I am using  RFC-compliant MIME extensions in combination with the polyfilled Blob interface (w/ data:URI fallback) provided by [FileSaver.js](https://github.com/eligrey/FileSaver.js/).
