### ISSUE TITLE
Why we are forced to use these buttons ?

### ISSUE THREAD

**Issue by leo2808** [clarketm/TableExport#40]
I not use buttons at all, can I create a custom triggers for this actions or download my file by Jquery or Javascript call ?

**Comment by CrestApps** [comment]
+1 I strongly suggest the same thing. 
Here are more examples of a different case use. I want to add a set of buttons on the top and another set at the bottom.

Another case, I want to utilize the `btn-group` class that bootstrap offers or event a drop downmenu.

In another use case, I am using css-bootstrap panel where the button's are located in a footer div and the table in the body.

You seems to be aiming for ease of use out of the box which is great. However, you may want to consider adding an option to not add the buttons above the table. Instead, allow the user to place them any place them any where the user wishes.

PS. This is a great package. keep up the good work.

**Comment by clarketm** [comment]
I have contrived a short-term *course of action* to combat this issue. In addition, I have conceived a more robust API to allow for dynamic exporting. Please provide feedback on this scheme so I can put together an expected timeline for these enhancements.

<h4>As a TableExport user, I would like to be able to ...</h4>

<hr>

- [ ]  **Disable the built-in buttons** via a *boolean* initialization property (e.g. `buttons: false`) with the *default* value set to `true`.

- [ ] **Supply my own button template** via a *string* plugin setting on the TableExport prototype (e.g. `buttonTemplate: "<button> ... </button>"`) with the *default* value set to the existing button element.   

- [ ] **Parse a table and dynamically export a specified filetype(s)** via the `.export()` API call 
```js
/* Run plugin and save it to a variable */
var tables = $("table").tableExport({ "buttons": false });

/* Export via API call */
tables.export("xls");     // filetype(s) {string|string[]}
```  
> This last one has a few performance and error-handling considerations that I need to work out. The general idea is to cache<sup>**[1]**</sup> the `TableExport` file blob(s), allowing the user to **export** *any* filetype with a simple call to `tables.export()`. 

<sup>**[1]**</sup> the file blob will be generated dynamically (not cached and retrieved) if the requested filetype(s) is not provided at initialization.

**Comment by CrestApps** [comment]
I would assume the following ability should be flexible enough to allow us to override the built in buttons.
````
$('.sometag').click(function(){
   table.export("xls");
});
````

**Comment by clarketm** [comment]
Button customization (including excluding buttons altogether) is now available in [v4.0.0](https://github.com/clarketm/TableExport/releases/tag/v4.0.0) via the `exportButtons` property. Here is an [example](https://www.travismclarke.com/tableexport/examples/exportButtons.html).

**Comment by CrestApps** [comment]
Thank you for this!

**Comment by ErrorPro** [comment]
Hey guys, the lib is cool but the interface of it too bad, it's too OOP. Just let people save files right away without forcing them to pass a button or whatever. I want to save a file by clicking on my own button, so I don't want to pass it anywhere all I need is this: `<button onClick={save} /> save => TableExport.export(myTableDOMNode, { fileName: 'myFile.xls' })`; Instead of it I have to create an instance of something, then I have to understand what methods it has and so on so on. Just use functions instead.

**Comment by dcy** [comment]
tError in v-on handler: "TypeError: table.export is not a function"
