### ISSUE TITLE
Version - v4.0.0-alpha.4 with webpack doesn't work correct in safari.

### ISSUE THREAD

**Issue by stas-o** [clarketm/TableExport#41]
From Safari -  can't find variable: view (line N227) in Blob.js module. In all other browsers it works fine. @clarketm  Can you take a look?

**Comment by GeoffreyBooth** [comment]
Confirmed that this happens in Browserify too. The fork of Blob.js that you’re using has a big glaring bug where it references a variable named `view` that is undefined. Compare https://github.com/clarketm/Blob.js/blob/master/Blob.js (used by TableExport) with https://github.com/eligrey/Blob.js/blob/master/Blob.js (the original)—in the process of forking, the declaration of `view` at the top was lost. The fork’s repo doesn’t have issues enabled, so we can’t report it there. @clarketm

**Comment by clarketm** [comment]
@GeoffreyBooth - you are 100% right - I missed a declaration along the way. Thanks for pointing the issue out. I have this fixed over in the [Blob.js](https://github.com/clarketm/Blob.js) repo now.
