### ISSUE TITLE
Extra spaces added to the cell which makes the column looks empty.

### ISSUE THREAD

**Issue by CrestApps** [clarketm/TableExport#42]
I have been trying recreate the same issue on a fiddler to explain the problem but a different problem is preventing me from doing so. Here is the fiddle to give you at least the html code that I am using https://jsfiddle.net/DTcHh/28806/

Here is a screenshot of the exact file the I downloaded "Columns D-Q appears to be empty columns"

![screenshot_1](https://cloud.githubusercontent.com/assets/24724371/22039387/f4b34f44-dcb3-11e6-9e74-4e92f27413cb.png)

After expanding column "F" or any column between D-Q you'll see the data.

![screenshot_2](https://cloud.githubusercontent.com/assets/24724371/22039415/0ab738e6-dcb4-11e6-888d-b21db4e63f26.png)

Also, you may want to convert any `<br>` or `<br />` to a new line when exporting html code.

**Comment by CrestApps** [comment]
What seems to be causing this problem are the whitespaces in the HTML code.

So this causes the problem

    <th class="text-center">
       Monday<br>
       01/16/2017
    </th>

But making the html code look like this fixes the problem.
    <th class="text-center">Monday<br> 01/16/2017</th>

I would suggest trimming the white spaces. Also, convert <br> to new line in excel.

**Comment by clarketm** [comment]
Thanks to @boonep and his much appreciated [PR](https://github.com/clarketm/TableExport/pull/44), this patch has been applied and will be slated for the **v3.3.8** release.
