### ISSUE TITLE
Can i change position of export buttons other than top/bottom?

### ISSUE THREAD

**Issue by bhumis** [clarketm/TableExport#46]
Seems there are 2 options to position default export buttons (Top/Bottom).
Is there a way i could position them anywhere else on the page, like may be in another div on the top of the page ?

This would be in a way resolved by: https://github.com/clarketm/TableExport/issues/40
But i was wondering if there is already an option for it ? I would like to use the existing export buttons.

**Comment by clarketm** [comment]
There isn't an efficient way to do this as of yet, aside from the very hacky DOM manipulation solution of moving the `<caption>` element after running `tableExport()`.

Something along the lines of this would work (using jQuery):
```js
var $myTable = $('table');
$myTable.tableExport();
var buttons = $myTable.find('caption').html();
$('#someOtherDiv').html(buttons);
```

**Comment by phbrazil** [comment]
Dude, you are fuc***ing awesome. Thanks

**Comment by phbrazil** [comment]
> There isn't an _efficient_ way to do this as of yet, it a WIP though as you pointed out in #40 .
> 
> ...although it is still _possible_. You could do a somewhat "hacky" DOM manipulation by moving the `<caption>` html (i.e. buttons) at some point after running `tableExport()` on your table.
> 
> Something along the lines of this would work (using jQuery):
> 
> ```js
> // Define the table you want to export
> var $myTable = $('#table');
> // Run `tableExport()`
> $myTable.tableExport();
> // Detach the `buttons` html
> var $buttons = $myTable.find('caption').children().detach();
> // Append the buttons to an element of your choosing
> $buttons.appendTo('#someOtherDiv');
> ```

Dude, you are fuc***ing awesome. Thanks
