### ISSUE TITLE
Blob.js Issue Breaks TableExport.js in Safari

### ISSUE THREAD

**Issue by piniondna** [clarketm/TableExport#47]
Blob.js trying to access an undefined object called view:
https://github.com/clarketm/Blob.js/blob/master/Blob.js#L227

In Chrome, the module loads fine, but Safari fails to even load module and halts all further execution.

Issue appears for me in Safari 10.
TableExport.js is being concatenated into a vendors.js file, which may be a contributing factor.

**Comment by clarketm** [comment]
@piniondna - This is fixed as of the latest [blobjs v1.1.1](https://github.com/clarketm/Blob.js/releases/tag/v1.1.1) release. Please let me know if the problem still persists.
