### ISSUE TITLE
Data exported should be different than the td text

### ISSUE THREAD

**Issue by janscas** [clarketm/TableExport#48]
Hi, I'have found that the data exported is in fact the td contents and there's no way to tell the table export that the value to be exported should be another (for example a data-value attribute on each td with a fall-back to the td's text)

I'm formatting the numbers with the Spanish format (dots are thousand separators and commas are decimal separators).

So, when exporting to excel, the values are not recognized as numbers.

What I would like to do is add the value to a data attribute on each td and that value goes to excel instead of the td text.

such as: 
`<td data-value="1526.56">1.526,56</td>`

Btw this should be very usefull in many other scenarios.

Any help on this?

**Comment by clarketm** [comment]
I know @danielgregorywilson has made some contributions and PRs that address the `type` (i.e. exporting an actual number) portion of your request. I need to circle back with him before I can get you any feedback of this, but assuming the functionality exists in `js-xlsx` and we can get this synced up with the [`alpha`]() release, which is supposed to supersede the jQuery-coupled implementation. I think we can get this fixed.

**Comment by clarketm** [comment]
@janscas - the *cell-types* and *type overrides* portion of your issue "formatting the numbers ... not recognized as numbers" is fixed (or rather, it has been added with the help of @danielgregorywilson) as of the latest release [v4.0.0](https://github.com/clarketm/TableExport/releases/tag/v4.0.0).

Cell value replacement with an `attribute` is not. Although with this latest release, direct access to the locally stored data is now available, meaning that you can create your own formatting, modification, buttons, etc. This is a robust way to do any processing you would like with the data, even allowing custom `export2file` triggers. Here is an [example](https://www.travismclarke.com/tableexport/examples/exportButtons.html) of this feature from [docs](https://tableexport.v4.travismclarke.com). 

<img width="272" alt="screen shot 2017-05-05 at 7 53 34 pm" src="https://cloud.githubusercontent.com/assets/9957358/25769391/4566d488-31cd-11e7-99bf-921cd9153519.png">

**Comment by janscas** [comment]
Thanks a lot. With this I can solve my problem.
And is usefull in many other ways.
