### ISSUE TITLE
Please correct bower.json

### ISSUE THREAD

**Issue by famu1hundred** [clarketm/TableExport#52]
The dependency on `xlsx-js` should be `js-xlsx`. This is causing issues when `js-xlsx` needs to be updated locally.

**Comment by famu1hundred** [comment]
From SheetsJS (js-xlsx):

> Our bower.json is configured to publish as js-xlsx. The manifest page appears to be correct.
xlsx-js points to a separate fork.
> It's likely that you either included both names in your bower.json, or a dependency pulls in the other version. I would check your local bower.json first.
> The correct name is noted in the README: https://github.com/sheetjs/js-xlsx#installation

**Comment by famu1hundred** [comment]
I submitted a PR for this

**Comment by clarketm** [comment]
@famu1hundred - I am well aware that `xlsx-js` is a fork, in fact, as you likely know, I was the one who forked it. At the time when I did fork,`js-xlsx` by SheetJS, was (*seemingly*) unmaintained, and there had been only one release in the two years prior. The fork was opinionated as specific to `TableExport`, so it would not have been fair to PR on SheetJS for my particular use-case. That has obviously changed, as I can now see that they have been cranking out patches almost every week and on the facade, there could likely be easy integration. So, I do agree with you that we should try to get `TableExport` synced back up with `js-xlsx`, but it is not safe to assume that the diverged library is compatible with `TableExport` until we at least contrive some unit tests to assert this premise. It would potentially introduce breaking changes if I were to accept your PR without performing the due diligence of performing tests. I don't think this will take more than a day or two, assuming I can free up some time, but in the mean time I can likely publish out a beta release that you can work from until this get's resolved.

**Comment by famu1hundred** [comment]
I can wait until you do your due diligence.

R

**Comment by clarketm** [comment]
fixed in [v4.0.0](https://github.com/clarketm/TableExport/releases/tag/v4.0.0)
