### ISSUE TITLE
Missing/invalid definitions for TypeScript

### ISSUE THREAD

**Issue by tompetko** [clarketm/TableExport#59]
I've spotted some missing or invalid definitions for Typescript:
 - `getExportData` method is missing in `TableExport` class
 - `tableexport` method should be `tableExport` in `JQuery` interface
 - `headings` property of `Defaults` object should be `headers`

I haven't checked the whole _.d.ts_ file yet.

**Comment by clarketm** [comment]
@tompetko – thanks for pointing this out. I have this as a [TODO](https://tableexport.v4.travismclarke.com/#todos) for the very near future. If you have any TS definition experience and have the bandwidth (and interest) to start a pull request, it would be greatly appreciated! Otherwise, I'll get this updated as soon as possible.

**Comment by amrsh** [comment]
+1: haven't been able to get this working from TypeScript, a working example would be great. Thanks!

**Comment by clarketm** [comment]
@tompetko – I see a bunch of syntax issues with the `tableexport.d.ts` file that might be causing the issue you mentioned in #24 (i.e. I am improperly using the `export` keyword which should be `declare`). I'll patch this and commit soon! @amrsh – after I push these changes it should fix your problem; if not, I can contrive an example.

**Comment by tompetko** [comment]
Thanks @clarketm for fixing, but according to the best practices it's good to export main class without using `default` keyword. Also, your `JQuery` interface has to be wrapped in `declare global` to be merged with existing `JQuery` declaration. I've created pull request: #60.

**Comment by amrsh** [comment]
Also, I am attempting to use without jquery, but this fails with webpack. Thanks for the quick turnaround!

**Comment by clarketm** [comment]
Thanks @tompetko for the pull request. I'll take a peek at the source, give it a test, and try to get that merged in ASAP.

**Comment by clarketm** [comment]
@amrsh – I'll look deeper into the Webpack issue, but in the mean time, it would be helpful if you could provide me with a snapshot of your project configuration and/or the errors that you are receiving along with the version of TableExport & Webpack. Please post that over in #24 and I work work towards a quick and effective resolution.
