### ISSUE TITLE
Ignore columns by name

### ISSUE THREAD

**Issue by tompetko** [clarketm/TableExport#62]
Support ignoring collumn not only by its number but also by its name, defined on `th` by attribute `data-field`. For example `<th data-field="Name">Name</th>`.

**Comment by clarketm** [comment]
@tompetko - currently cell-level cell hiding and ignoring is available via class attributes, `.tableexport-empty` and `.tableexport-ignore` respectively. Here is an [example](https://www.travismclarke.com/tableexport/examples/ignore-row-cols-cells.html#ignore-cell-table). I have a slated [feature enhancement](https://tableexport.v4.travismclarke.com/#todos) to take these aforementioned customizable classes and convert them to customizable CSS selector(s) `selector|selector[]` which would work well for *attributes* (e.g. `[data-field=Name]`). This is actually something I am working on now and will infuse in the next release.

**Comment by clarketm** [comment]
@tompetko – I published this change in [`v5.0.0-rc.7`](https://github.com/clarketm/TableExport/releases/tag/v5.0.0-rc.7). Expect this to become the **v5.0.0** stable release in the coming week!
