### ISSUE TITLE
how to import in angular 4

### ISSUE THREAD

**Issue by lanzosuarez** [clarketm/TableExport#65]
can i ask how can i use this in angular 4?

**Comment by clarketm** [comment]
It should be as simple as:
```js
import {TableExport} from "tableexport"
...
new TableExport(...)
```

Are you getting any errors?

**Comment by clarketm** [comment]
@jorgeandresserrano, @lanzosuarez – It appears that there is a critical bug with either the module loading or exporting. I will patch this ASAP.

**Comment by jorgeandresserrano** [comment]
@clarketm `import {TableExport} from "tableexport"` was not failing on my case. However, under version v4.0.8 it's fixed. Great support! Thanks Clark.
