### ISSUE TITLE
Data exported is different

### ISSUE THREAD

**Issue by rinoa96** [clarketm/TableExport#66]
Hi, as described in issue number #48 , I have a problem with data export in .xlsx (.txt work fine).
I have a table with 3 columns: "First Data", "Second Data", "Third Data". When I try to export table, in the .xlsx file only the Third Column contains wrong data (all cell in this column contain "04/11/2017  23:00:00" instead of dd/mm/yyyy data).
I'm using these sources:

> https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.10.2/xlsx.core.min.js
https://cdnjs.cloudflare.com/ajax/libs/blob-polyfill/1.0.20150320/Blob.js"
https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.3/FileSaver.js"
https://cdnjs.cloudflare.com/ajax/libs/TableExport/4.0.3/js/tableexport.min.js
https://www.google-analytics.com/analytics.js

And before body end tag I have this:

`<script>`
 ` TableExport.prototype.bootstrap = ["btn", "btn-default", "btn-toolbar"];`
`  var  indexcol = 11;`
  `  var $e = jQuery.noConflict();`
   ` $e(BootstrapTable).tableExport({`
      `  headings: true,                    // (Boolean), display table headings (th/td elements) in the <thead>`
     `   footers: true,                     // (Boolean), display table footers (th/td elements) in the <tfoot>`
    `    formats: ["xlsx", "txt"],    // (String[]), filetypes for the export`
    `    fileName: "id",                    // (id, String), filename for the downloaded file`
    `    bootstrap: true,                   // (Boolean), style buttons using bootstrap`
     `   position: "top",                 // (top, bottom), position of the caption element relative to table`
     `   ignoreRows: null,                  // (Number, Number[]), row indices to exclude from the exported file(s)`
      `  ignoreCols: indexcol,             // (selector, selector[]), selector(s) to replace cells with an empty` `//string in the exported file(s)`
      `  trimWhitespace: false              // (Boolean), remove all leading/trailing newlines, spaces, and tabs` `from cell text in the exported file(s)`
`    });`
 `   document.getElementsByClassName('xlsx')[0].type= 'button'; //type button to prevent form submit`
  `  document.getElementsByClassName('txt')[0].type= 'button'`
`</script>`

I don't understand how to fix it. Any help would be appreciated.

**Comment by clarketm** [comment]
You can add the `tableexport-date` class to any `<td>` or `<th>` to force a date type in Excel.
**e.g.**
```js
<td class="tableexport-date">4/11/1975</td>
```

What are the original values inside the HTML before calling `TableExport`?

**Comment by clarketm** [comment]
@rinoa96 – I have fixed this issue and published the patch in [v4.0.5](https://github.com/clarketm/TableExport/releases/tag/v4.0.5)

**Comment by meghalv** [comment]
> You can add the `tableexport-date` class to any `<td>` or `<th>` to force a _date_ type in Excel.
> **e.g.**
> 
> ```js
> <td class="tableexport-date">4/11/1975</td>
> ```
> 
> What are the original values inside the HTML before calling `TableExport`?

I had a similar issue of any table data containing 2 hyphens "-" would be automatically interpreted as a Date 
e.g. Marka_WEB-generic-001
would be exported as a date 31-01-2001

Your solution worked in my case too except what i added was the string class :
`<td` class='tableexport-string'>  Marka_WEB-generic-001 `</td>`
