### ISSUE TITLE
Table not exported when dynamically generated on Angular4

### ISSUE THREAD

**Issue by jorgeandresserrano** [clarketm/TableExport#68]
Static html tables have no problem but when the content is generated through angular it just does not export it. For instance, the following will not get exported:
```
<tr *ngFor="let item of items">
    <td>{{ item.id }}</td>
    <td>{{ item.name }}</td>
</tr>
```

**Comment by clarketm** [comment]
@jorgeandresserrano 

So for the initial render, you should initialize `TableExport` in one of the [AfterContent](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#aftercontent) lifecycle hooks to ensure the DOM is rendered (which it sounds like you are doing).

... then to handle dynamic updates from *Angular*, call the `TableExport` [`update()`](https://github.com/clarketm/TableExport#update) or [`reset()`](https://github.com/clarketm/TableExport#reset) method when any of the `properties` in your table change; I am not an Angular user, but I think you can do this with [`OnChanges`](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#onchanges).

I will verify this and get back to you ASAP!

**Comment by jorgeandresserrano** [comment]
@clarketm I was using the lifecycle hook `ngAfterViewInit()` but was not working, so then I went a step further and `ngAfterViewChecked()` is working fine. So it may be a good idea to somehow update the documention to advise about initializing TableExport at `ngAfterViewChecked()` hook.

**Comment by clarketm** [comment]
@jorgeandresserrano – thanks for the quick feedback. I will update the documentation. I have also added an example exactly like this one (i.e. using `ngFor` inside the `ngAfterViewChecked `) over in the [`tableexport_angular4_webpack2_app`](https://github.com/clarketm/tableexport_angular4_webpack2_app) skeleton which I have also linked on the [`TableExport`](https://github.com/clarketm/TableExport) README.

```js
  public ngAfterViewChecked() {
    // NOTE: the `reset` is to prevent multiple renders on state change
    TableExport(document.querySelector('#default-table')).reset();
  }
```
