### ISSUE TITLE
Excel cell merge support

### ISSUE THREAD

**Issue by clarketm** [clarketm/TableExport#69]
Allow for cell merging in Excel (`xlsx`/`xls`) format that corresponds to the `rowspan` and `colspan` attributes applied to a series of table cells (`<td>` or `<th>`).

**Comment by dulguun00** [comment]
The problem with several consecutive colspan is fix ?

![screen shot 2017-06-06 at 16 05 15](https://cloud.githubusercontent.com/assets/4251096/26819553/5c0d0b00-4ada-11e7-8a6d-a43a3a56ec77.png)

to

![screen shot 2017-06-06 at 16 06 57](https://cloud.githubusercontent.com/assets/4251096/26819598/93ed01c4-4ada-11e7-8b6d-a8b7b550a6df.png)

**Comment by clarketm** [comment]
@dulguun00 – I reopened #27. Looks like I may need to handle `rowspan` and `colspan` differently in the parsing. I'll try to get this fixed soon.

**Comment by danmaidesenling** [comment]
why i still not work on "Excel cell merge"  
i get v5.0.0-rc.6 tableexport.js
![qq 20170609144633](https://user-images.githubusercontent.com/7588416/26964069-7e444e00-4d22-11e7-8d97-03f64e4762a4.png)
![qq 20170609144650](https://user-images.githubusercontent.com/7588416/26964070-7e45890a-4d22-11e7-96b7-7fb353dbb590.png)

**Comment by clarketm** [comment]
@danmaidesenling – Can you do two things for me to assist me with identifying the issue?
1. Log out or verify that the version of *TableExport* is `>= 5.0.0-rc.6` 
![image](https://user-images.githubusercontent.com/9957358/26987849-ee246d84-4d01-11e7-881a-33820571c28b.png)
2. Show me the structure of your `html`. It is difficult for me to fix without seeing the `<table>` structure
