### ISSUE TITLE
QA/Test v5.0.0-rc.10 and prepare for release v5.0.0

### ISSUE THREAD

**Issue by clarketm** [clarketm/TableExport#73]
- [x] QA/Test [v5.0.0-rc.11](https://github.com/clarketm/TableExport/releases/tag/v5.0.0-rc.11)
- [x] Write usage documentation for *v5.0.0*
- [x] Write migration guide for *v4* -> *v5*

**Comment by soukupl** [comment]
how can I help? 
I just implemented last build of v5.0.0-rc and seems to work ok with big tables :)

**Comment by clarketm** [comment]
@soukupl – I want to start by saying sorry for not getting back to you sooner; it has been a busy month for me. I want to thank you for taking the time to review the project and provide feedback. I have begun the `migration guide for v4 -> v5` this week. Assuming none of the existing, high priority issues are pertinent to v5, the plan is to prepare a stable release by the 8/15. PDF support is the only feature that will not be included in this release.
