### ISSUE TITLE
Way to keep the leading zero in a number after export

### ISSUE THREAD

**Issue by blackrest80** [clarketm/TableExport#75]
Dear Clarketm

I want to keep the leading zero in a number but I don't find any solution in your guide. Can you help me ?

Thanks you so much

**Comment by clarketm** [comment]
@blackrest80 – you can achieve this by leveraging the *cell-data-type* classes:
![image](https://user-images.githubusercontent.com/9957358/28093340-bb68ebd2-664b-11e7-852f-504af04485f1.png)

For example, if you add the `tableexport-string` class to the cell (`<td>`) then the zero prefix will be retained. If you want more granular control over what is formatted as a number, then you can provide your own `typeConfig` function like so:
```js
TableExport.prototype.typeConfig.number.assert = function (value) { ... };
```

**Comment by clarketm** [comment]
@blackrest80 – When I have some time, I will add a `format` property to these data types to allow the user to supply a [*format string*](https://github.com/SheetJS/js-xlsx#number-formats).
