### ISSUE TITLE
can't export chinese..

### ISSUE THREAD

**Issue by Orz-Li** [clarketm/TableExport#79]
to support chinese need use base64 encode. i think you should create an argument to choose use base64 encode or  not.

**Comment by clarketm** [comment]
This [example](https://tableexport.v3.travismclarke.com/examples/rowspan-colspan.html) demonstrates a table with Chinese characters. Does this export properly on your device? If not, there may be either a configuration or device/application compatibility issue.

**Comment by Orz-Li** [comment]
it worked..it is looks like my configuration problem.
