### ISSUE TITLE
Why my button is always on the top of table? 

### ISSUE THREAD

**Issue by er1iang** [clarketm/TableExport#9]
I am using `TableExport.js v3.2.5`.

The download button  is always on the top of table even I set the settings clearly.

The library is simple to use, but it could be perfect if I can customize it more flexibly.

Thanks for your work! :+1:

**Comment by er1iang** [comment]
Sorry I forgot add css in my page  ....

**Comment by clarketm** [comment]
In the releases since this issue was filed (and resolved), I added additional mechanisms to style the `<caption>` element that encapsulates the export button. Please refer to #151 for a summary of those options.
